name: 'gotphoto_case_study'
version: '1.0.0'
config-version: 2

profile: 'gotphoto_snowflake'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
    - "logs"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  elementary:
    +schema: 'elementary'
    +enabled: true
  gotphoto_case_study:
    staging:
      +docs:
        node_color: "#cd7f32"
      +materialized: table
      +tags: ['staging']
      +schema: 'staging'
    intermediate:
      +docs:
        node_color: "#4c72b0"
      +materialized: table
      +tags: ['intermediate']
      +schema: 'intermediate'
    mart:
      +docs:
        node_color: "#55a868"
      +materialized: table
      +tags: ['mart']
      +schema: 'mart'