name: 'gotphoto_case_study'
version: '1.0.0'
config-version: 2

profile: 'gotphoto_snowflake'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
    - "logs"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  gotphoto_case_study:
    staging:
      +materialized: table
      +tags: ['staging']
      +schema: 'STAGING'