name: 'gotphoto_case_study'
version: '1.0.0'
profile: 'gotphoto_snowflake'

model-paths: ['models']
test-paths: ['tests']
macro-paths: ['macros']

target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
    - "logs"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  dbt_project_bigquery:
    staging:
      +materialized: table
      +tags: ['staging']
      +schema: 'staging'
    mart:
      +materialized: table
      +tags: ['mart']
      +schema: 'mart'