version: 2

models:
  - name: stg_region
    description: "Region dimension table."
    columns:
      - name: region_key
        tests:
          - unique
          - not_null
      - name: region_name
        tests:
          - not_null
      - name: region_comment

  - name: stg_nation
    description: "Nation dimension table."
    columns:
      - name: nation_key
        tests:
          - unique
          - not_null
      - name: nation_name
        tests:
          - not_null
      - name: region_key
        tests:
          - relationships:
              to: ref('stg_region')
              field: region_key
      - name: nation_comment

  - name: stg_supplier
    description: "Supplier dimension table."
    columns:
      - name: supplier_key
        tests:
          - unique
          - not_null
      - name: supplier_name
        tests:
          - not_null
      - name: nation_key
        tests:
          - relationships:
              to: ref('stg_nation')
              field: nation_key
      - name: supplier_address
      - name: supplier_phone
      - name: supplier_acctbal
      - name: supplier_comment

  - name: stg_customer
    description: "Customer dimension table."
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: customer_name
        tests:
          - not_null
      - name: nation_key
        tests:
          - relationships:
              to: ref('stg_nation')
              field: nation_key
      - name: customer_address
      - name: customer_phone
      - name: customer_acctbal
      - name: customer_mktsegment
      - name: customer_comment

  - name: stg_part
    description: "Part dimension table."
    columns:
      - name: part_key
        tests:
          - unique
          - not_null
      - name: part_name
        tests:
          - not_null
      - name: part_mfgr
      - name: part_brand
      - name: part_type
      - name: part_size
      - name: part_container
      - name: part_retailprice
      - name: part_comment

  - name: stg_partsupp
    description: "Part-Supplier fact table."
    columns:
      - name: part_key
        tests:
          - relationships:
              to: ref('stg_part')
              field: part_key
      - name: supplier_key
        tests:
          - relationships:
              to: ref('stg_supplier')
              field: supplier_key
      - name: avail_qty
      - name: supply_cost
      - name: partsupp_comment

  - name: stg_orders
    description: "Orders fact table."
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: customer_key
        tests:
          - relationships:
              to: ref('stg_customer')
              field: customer_key
      - name: order_status
      - name: total_price
      - name: order_date
      - name: order_priority
      - name: clerk
      - name: ship_priority
      - name: order_comment

  - name: stg_lineitem
    description: "Line Item fact table."
    columns:
      - name: order_key
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_key
      - name: part_key
        tests:
          - relationships:
              to: ref('stg_part')
              field: part_key
      - name: supplier_key
        tests:
          - relationships:
              to: ref('stg_supplier')
              field: supplier_key
      - name: line_number
      - name: quantity
      - name: extended_price
      - name: discount
      - name: tax
      - name: return_flag
      - name: line_status
      - name: ship_date
      - name: commit_date
      - name: receipt_date
      - name: ship_instruct
      - name: ship_mode
      - name: lineitem_comment
