version: 2
sources:
  - name: tpch_sf1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: region
      - name: nation
      - name: supplier
      - name: customer
      - name: part
      - name: partsupp
      - name: orders
      - name: lineitem
