gotphoto_snowflake:
  outputs:
    sandbox:
      account: jq81284.europe-west3.gcp
      database: ANALYTICS_DB
      password: 'EPl3X7WocDZ71M'
      role: ACCOUNTADMIN
      schema: DEFAULT
      type: snowflake
      user: sarinravishanker
      warehouse: COMPUTE_WH
      client_session_keep_alive: False
  target: sandbox
      # Other environment-specific configurations can be added here

