gotphoto_snowflake:
  outputs:
    sandbox:
      account: jq81284.europe-west3.gcp
      database: ANALYTICS_DB
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: DEFAULT
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      warehouse: COMPUTE_WH
      client_session_keep_alive: False
  target: sandbox
      # Other environment-specific configurations can be added here

